### ISSUE TITLE
Scenes -> New (create scene without file) feature: fails due to initial state of Cover Image; with workaround, the resulting submitted draft does not load on stashdb.org

### ISSUE THREAD

**Issue by nrg101** [stashapp/CommunityScrapers#1203]
I've just updated to v0.18.0 and was looking at the Scenes -> New  feature, tried a couple URLs and I get this error:

```
Something went wrong.
Details
TypeError: Cannot read properties of undefined (reading 'screenshot')
at Yt (http://10.204.79.206:9999/assets/SceneEditPanel.347d7d01.js:1:3234) at div at div at O (http://10.204.79.206:9999/assets/SceneCreate.5f2d7181.js:1:882) at t (http://10.204.79.206:9999/assets/index.79285eb5.js:114:6930) at t (http://10.204.79.206:9999/assets/index.79285eb5.js:114:8887) at D (http://10.204.79.206:9999/assets/Scenes.3a1bd0d6.js:1:4213) at t (http://10.204.79.206:9999/assets/index.79285eb5.js:114:6930) at t (http://10.204.79.206:9999/assets/index.79285eb5.js:114:8887) at Suspense at V4 (http://10.204.79.206:9999/assets/index.79285eb5.js:2549:5212) at div at cae (http://10.204.79.206:9999/assets/index.79285eb5.js:2551:2328) at Qoe (http://10.204.79.206:9999/assets/index.79285eb5.js:2549:10474) at EH (http://10.204.79.206:9999/assets/index.79285eb5.js:153:46784) at Suspense at wH (http://10.204.79.206:9999/assets/index.79285eb5.js:153:45328) at soe (http://10.204.79.206:9999/assets/index.79285eb5.js:2544:43937) at t (http://10.204.79.206:9999/assets/index.79285eb5.js:149:3813) at V4 (http://10.204.79.206:9999/assets/index.79285eb5.js:2549:5212) at gme (http://10.204.79.206:9999/assets/index.79285eb5.js:2592:18289) at zF (http://10.204.79.206:9999/assets/index.79285eb5.js:85:2518) at t (http://10.204.79.206:9999/assets/index.79285eb5.js:114:3677) at t (http://10.204.79.206:9999/assets/index.79285eb5.js:114:9961)
```

I guess one of the `scene.paths.screenshot` references isn't "checked" with an optional chain or whatever

example URL that causes this error for me: https://www.evilangel.com/en/video/evilangel/Anal-Training/216601

maybe the `if (srcScene?.paths.screenshot) {` in `ui/v2.5/src/components/Scenes/SceneDetails/SceneCreate.tsx` ?
(for a srcScene without a paths property)

if I select a Cover Image from File _first_, and _then_ Scrape the URL, it works!
so some sort of issue with the image being undefined initially

**Comment by nrg101** [comment]
also, when I submitted another scene created with this feature, when I attempt to view the draft on stashdb, the draft page does not load (it's just the blank stashdb page background colour with no content) and the following errors in console:

```
react-dom.production.min.js:216 TypeError: Cannot read properties of undefined (reading 'duration')
    at eDe (parse.ts:72:39)
    at tDe (SceneDraft.tsx:68:36)
    at GN (react-dom.production.min.js:157:137)
    at l6 (react-dom.production.min.js:267:460)
    at a6 (react-dom.production.min.js:250:347)
    at lz (react-dom.production.min.js:250:278)
    at hc (react-dom.production.min.js:250:138)
    at Ab (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at e.unstable_runWithPriority (scheduler.production.min.js:18:343)
bb @ react-dom.production.min.js:216
module.js:62 Uncaught TypeError: Cannot read properties of undefined (reading 'duration')
    at eDe (parse.ts:72:39)
    at tDe (SceneDraft.tsx:68:36)
    at GN (react-dom.production.min.js:157:137)
    at l6 (react-dom.production.min.js:267:460)
    at a6 (react-dom.production.min.js:250:347)
    at lz (react-dom.production.min.js:250:278)
    at hc (react-dom.production.min.js:250:138)
    at Ab (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at e.unstable_runWithPriority (scheduler.production.min.js:18:343)
manifest.json:1          Failed to load resource: the server responded with a status of 404 ()
```

**Comment by nrg101** [comment]
This was an issue in `stashapp` that has since been resolved with a bugfix included a release
