### ISSUE TITLE
can't get AyloAPI to work, help needed 

### ISSUE THREAD

**Issue by steven3854** [stashapp/CommunityScrapers#1661]
hi all i cant get the Aylo Api to work it keeps on coming up with "could not unmarshal json from script output eof"
looking at the logs i think it having issues wit the code possably??? (but more likly user error) any help would be apprciated.

my log for it: 

24-02-22 16:27:13Error   scrapeSceneURL: input: scrapeSceneURL could not unmarshal json from script output: EOF
2024-02-22 16:27:13Error   could not unmarshal json from script output: EOF
2024-02-22 16:27:13Error   [Scrape / Bromo] ImportError: cannot import name 'Required' from 'typing' (C:\Users\steve\AppData\Local\Programs\Python\Python310-32\lib\typing.py)
2024-02-22 16:27:13Error   [Scrape / Bromo]     from typing import Literal, Required, TypedDict
2024-02-22 16:27:13Error   [Scrape / Bromo]   File "C:\Users\steve\.stash\scrapers\community\py_common\types.py", line 1, in <module>
2024-02-22 16:27:13Error   [Scrape / Bromo]     from py_common.types import (
2024-02-22 16:27:13Error   [Scrape / Bromo]   File "C:\Users\steve\.stash\scrapers\community\AyloAPI\scrape.py", line 13, in <module>
2024-02-22 16:27:13Error   [Scrape / Bromo]     from AyloAPI.scrape import (
2024-02-22 16:27:13Error   [Scrape / Bromo]   File "C:\Users\steve\.stash\scrapers\community\Bromo\Bromo.py", line 6, in <module>
2024-02-22 16:27:13Error   [Scrape / Bromo] Traceback (most recent call last):
2024-02-22 16:27:13Warning unable to use configured python path: CreateFile  : The system cannot find the path specified.

this happens with all the sites that use AyloAPI

**Comment by Maista6969** [comment]
You'll need to update your Python version to 3.11 or higher: I recommend getting the newest stable version from python.org and installing it _outside_ of your Users folder. At the time of this writing that's [Python 3.12.2](https://www.python.org/downloads/release/python-3122/). Remember to check the box that adds python to your PATH variable during installation.

After installing it you will need to manually install some Python packages: `py -m pip install stashapp-tools requests beautifulsoup4 cloudscraper lxml` will be enough for most scrapers and plugins 🙂

If you still get the error that says `Warning unable to use configured python path: CreateFile : The system cannot find the path specified.` you can set the Python path directly in `Settings > System > Application Paths`

**Comment by steven3854** [comment]
where would you recomend installing the python path? would it work at the root fo the file system? also when doing a look through i stash app in the setting > system, i can't see application paths? sorry for the questions, when i was using the MindGeekAPI it just worked and then i upgaded the app and downloaded the CommunityScrapers  through stash.

**Comment by Maista6969** [comment]
I have installed mine at `C:\Python312` and set the Python path to `C:/Python312/python.exe` (in the aforementioned `Settings > System` under the `Application Paths` heading)
![image](https://github.com/stashapp/CommunityScrapers/assets/131594657/a9a4e261-732b-47fc-be68-e9fb35d0b9af)

**Comment by steven3854** [comment]
sorted thank you!!
