### ISSUE TITLE
pmvhaven scraper still not working

### ISSUE THREAD

**Issue by 4cz36sae** [stashapp/CommunityScrapers#2045]
(this is important, be as detailed as you can)

Are you scraping a scene, gallery, movie, or performer?
Scrape with URL? If so, what URLs have you tried?  
Scrape with fragment? If so, what is the filename / title / studio code?  
Scrape with name? Give an example you searched for that caused the scraper to fail

Please check the logs to see if there are any relevant error messages you can include

receiving the below error when scraping https://pmvhaven.com/video/I-Can-Make-You-Cum-PMV_66181f77ffb1d3f7a4ba52d2
```

2024-09-27 09:08:29
Error   
scrapeSceneURL: input: scrapeSceneURL could not unmarshal json from script output: EOF
2024-09-27 09:08:29
Error   
could not unmarshal json from script output: EOF
2024-09-27 09:08:29
Error   
[Scrape / PMVHaven]     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
2024-09-27 09:08:29
Error   
[Scrape / PMVHaven] requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-09-27 09:08:29
Error   
[Scrape / PMVHaven]            ^^^^^^^^^^
2024-09-27 09:08:29
Error   
[Scrape / PMVHaven]     return req.json()
2024-09-27 09:08:29
Error   
[Scrape / PMVHaven]   File "/usr/lib/python3.12/site-packages/requests/models.py", line 978, in json
2024-09-27 09:08:29
Error   
[Scrape / PMVHaven]            ^^^^^^^^^^^^^^^^
2024-09-27 09:08:29
Error   
[Scrape / PMVHaven]   File "/root/.stash/scrapers/community/PMVHaven/PMVHaven.py", line 24, in getData
2024-09-27 09:08:29
Error   
[Scrape / PMVHaven]     data = getData(sceneId)
2024-09-27 09:08:29
Error   
[Scrape / PMVHaven]            ^^^^^^^^^^^^^^^^^^^^^
2024-09-27 09:08:29
Error   
[Scrape / PMVHaven]   File "/root/.stash/scrapers/community/PMVHaven/PMVHaven.py", line 56, in getVideoById
2024-09-27 09:08:29
Error   
[Scrape / PMVHaven]     data = getVideoById(sceneId)
2024-09-27 09:08:29
Error   
[Scrape / PMVHaven]   File "/root/.stash/scrapers/community/PMVHaven/PMVHaven.py", line 122, in sceneByURL
2024-09-27 09:08:29
Error   
[Scrape / PMVHaven]                      ^^^^^^^^^^^^^^^^^^
2024-09-27 09:08:29
Error   
[Scrape / PMVHaven]   File "/root/.stash/scrapers/community/PMVHaven/PMVHaven.py", line 132, in <module>
2024-09-27 09:08:29
Error   
[Scrape / PMVHaven] Traceback (most recent call last):
2024-09-27 09:08:29
Error   
[Scrape / PMVHaven]     print(json.dumps(sceneByURL(params)))
2024-09-27 09:08:29
Error   
[Scrape / PMVHaven] During handling of the above exception, another exception occurred:
2024-09-27 09:08:29
Error   
[Scrape / PMVHaven] json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-09-27 09:08:29
Error   
[Scrape / PMVHaven]     raise JSONDecodeError("Expecting value", s, err.value) from None
2024-09-27 09:08:29
Error   
[Scrape / PMVHaven]   File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
2024-09-27 09:08:29
Error   
[Scrape / PMVHaven]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-27 09:08:29
Error   
[Scrape / PMVHaven]     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2024-09-27 09:08:29
Error   
[Scrape / PMVHaven]   File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
2024-09-27 09:08:29
Error   
[Scrape / PMVHaven]            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-27 09:08:29
Error   
[Scrape / PMVHaven]     return _default_decoder.decode(s)
2024-09-27 09:08:29
Error   
[Scrape / PMVHaven]   File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
2024-09-27 09:08:29
Error   
[Scrape / PMVHaven]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-27 09:08:29
Error   
[Scrape / PMVHaven]     return complexjson.loads(self.text, **kwargs)
2024-09-27 09:08:29
Error   
[Scrape / PMVHaven] Traceback (most recent call last):
2024-09-27 09:08:29
Error   
[Scrape / PMVHaven]   File "/usr/lib/python3.12/site-packages/requests/models.py", line 974, in json

```

**Comment by feederbox826** [comment]
Seems fine on my end, do you get the same error with a VPN on stash?

**Comment by kman-spec** [comment]
Have the same issue at my end. I am unable to share the entire logs currently.

**Comment by feederbox826** [comment]
Still unable to replicate, please come back with logs or try with a VPN
